### ISSUE TITLE
graphql.error.located_error.GraphQLLocatedError: name 'get_hackers' is not defined

### ISSUE THREAD

**Issue by athul** [upsidetravel/graphene-pydantic#16]
I'm sorry for the title being vague but I didn't know how to present to you the problem.

Basically I was trying to hack up an API using FastAPI, Pydantic and GraphQL. I found this repo from an Issue there. 
Following the readme, I couldn't query the data using GraphiQl(I hacked starlette and currently running on graphql playground).
for this query
```gql
query {
  hackers {
    id
  }
}
```
I'm getting an error like this
```json
{
  "error": {
    "data": {
      "hackers": null
    },
    "errors": [
      {
        "message": "name 'get_hackers' is not defined",
        "locations": [
          {
            "line": 2,
            "column": 3
          }
        ],
        "path": [
          "hackers"
        ]
      }
    ]
  }
}
```
My Pydantic Basemodel and ObjectType as 
```py
class HackerModel(BaseModel):
    id: int
    name: str
    college: str
    email: str
    dob: date

class Hacker(PydanticObjectType):
    class Meta:
        model = HackerModel
        only_fields=("name","college","id","email","dob")
    class Config:
        arbitrary_types_allowed = True
```
And my Query Class Looks like this
```py
class Query(graphene.ObjectType):
    hackers = graphene.List(Hacker)
    def resolve_hackers(self, info):
        return get_hackers()
```

I only followed your Readme Example . Any idea on How to resolve this?

**Comment by dantheman39** [comment]
Hello @athul !  In the last line of your code here (`return get_hackers()`), you have to actually implement the function `get_hackers()` somewhere. (We indicate that in the README with a comment).

The README is just an overview giving you the most important points. If you want a full complete working example, you can look in the [examples folder](https://github.com/upsidetravel/graphene-pydantic/tree/master/examples).

Here's a fully functioning version of your code, with `get_hackers()` implemented:

```python
from datetime import date
import graphene
from graphene_pydantic import PydanticObjectType
from pydantic import BaseModel


class HackerModel(BaseModel):
    id: int
    name: str
    college: str
    email: str
    dob: date


class Hacker(PydanticObjectType):
    class Meta:
        model = HackerModel


def get_hackers():

    frank_the_hacker = Hacker(
        id=1,
        name="Frank",
        college="Georgetown",
        email="frank@georgetown.edu", 
        dob=date(1979, 12, 25),
    )
    return [frank_the_hacker]


class Query(graphene.ObjectType):
    hackers = graphene.List(Hacker)
    def resolve_hackers(self, info):
        return get_hackers()


if __name__ == "__main__":
    from graphql.execution.executors.sync import SyncExecutor
    import json

    schema = graphene.Schema(query=Query)
    result = schema.execute(
        """
        query {
          hackers {
            id
          }
        }
        """,
        executor=SyncExecutor(),
        return_promise=False,
    )
    print(result.errors)
    print(json.dumps(result.data, indent=2))
```

**Comment by athul** [comment]
Oh Okay, thanks❤️

**Comment by athul** [comment]
So you're saying that, I'd have to hard code the data like this
```py
frank_the_hacker = Hacker(
        id=1,
        name="Frank",
        college="Georgetown",
        email="frank@georgetown.edu", 
        dob=date(1979, 12, 25),
    )
    return [frank_the_hacker]
```

So is there anyway I could fetch query data from a DB using Graphiql rather than fetching from a hardcoded query in the Script? I'm hoping to use that with FastAPI framework and Sqlalchemy for the DB operations

**Comment by BoyangHuang** [comment]
@athul You definitely don't have to hard code the data like that. I think @dantheman39 was just providing a simple example that returned a list of Hacker instances.

**Comment by dantheman39** [comment]
Yep @BoyangHuang said it. I would think at some point in your app you would do something like read from a database and convert each line into a Hacker instance, something like (pseudo code):

```python
import typing as T
# get your DB set up
def get_hackers_by_name(name: str) -> T.List[Hacker]:
    with DB.connect() as conn:
        raw_result = conn.execute(f"select * from hackers where name = '{name}'")
        hackers = []
        for raw_hacker in raw_result:
            hackers.append(
                Hacker(
                    id=raw_hacker.id,
                    etc...
                )
            )
        return hackers
    
```

**Comment by athul** [comment]
Thanks for the feedback ❤️❤️ Thanks for the framework too.

I'm sorry if I was being silly too and Holiday Greetings :tada: :tada:
