### ISSUE TITLE
Pydantic 1.3+ support

### ISSUE THREAD

**Issue by alexhafner** [upsidetravel/graphene-pydantic#17]
Hi there, thanks for creating the graphene-pydantic project :-) graphene-pydantic is currently locked into Pydantic version <=1.1,>=0.26

Do you have plans to keep up with the pydantic releases, or will you only update from time to time?

**Comment by necaris** [comment]
@alexhafner thanks for the comment! We're honestly not following every release that closely so we'll lag a little bit behind, but certainly aim to be up to date if we can!

**Comment by alexhafner** [comment]
great - many thanks for the clarification

**Comment by necaris** [comment]
FYI, this is closed by https://github.com/upsidetravel/graphene-pydantic/commit/7de7852be0d65b1422382e9399180460d90d2729
