### ISSUE TITLE
Published artifact for 0.0.6 specifies Pydantic <= 1.3

### ISSUE THREAD

**Issue by seansfkelley** [upsidetravel/graphene-pydantic#22]
I'm a little confused how this happened, but 0.0.6 on PyPI specifies Pydantic <= 1.3, even though master specifies <= 1.4 and there don't appear to be any intervening commits.

Also, FYI, there is no tag that GitHub can see for 0.0.6.

**Comment by necaris** [comment]
Huh. No idea how this happened either, although there's a chance that the lockfile wasn't up to date. #23 should fix this, with another release.

**Comment by necaris** [comment]
@seansfkelley please have a look at 0.0.7, now on PyPI, which should fix this problem and be consistent with master.

**Comment by seansfkelley** [comment]
Looks good, thank you very much!
